-- 1. Write an SQL query to retrieve a list of all orders along with customer information (e.g., customer name) for each order. 
SELECT O.OrderID, C.FirstName, C.LastName 
FROM Orders as O
INNER JOIN Customers as C
ON O.CustomerID=C.CustomerID

-- 2. Write an SQL query to find the total revenue generated by each electronic gadget product. Include the product name and the total revenue. 
SELECT P.ProductName, SUM(OD.Quantity*P.Price) as TotalRevenue
FROM OrderDetails as OD
INNER JOIN Products as P
ON OD.ProductID=P.ProductID
GROUP BY P.ProductName


-- 3. Write an SQL query to list all customers who have made at least one purchase. Include their names and contact information. 
SELECT FirstName, LastName, Phone 
FROM Orders AS O
INNER JOIN Customers AS C
ON O.CustomerID = C.CustomerID

-- 4. Write an SQL query to find the most popular electronic gadget, which is the one with the highest total quantity ordered. Include the product name and the total quantity ordered. 
SELECT TOP 1 P.ProductName,SUM(OD.Quantity) AS TotalQuantityOrdered
FROM Products P
INNER JOIN OrderDetails OD
ON P.ProductID = OD.ProductID
GROUP BY P.ProductName
HAVING SUM(OD.Quantity) = (SELECT MAX(OD.Quantity))
-- 5. Write an SQL query to retrieve a list of electronic gadgets along with their corresponding categories. 

-- 6. Write an SQL query to calculate the average order value for each customer. Include the customer's name and their average order value. 
SELECT C.FirstName, C.LastName, AVG(O.TotalAmount) AS AverageOrderValue
FROM Orders AS O
INNER JOIN Customers AS C
ON O.CustomerID = C.CustomerID
GROUP BY O.CustomerID, C.FirstName, C.LastName
-- 7. Write an SQL query to find the order with the highest total revenue. Include the order ID, customer information, and the total revenue. 
SELECT TOP 1 O.OrderID, C.FirstName, C.LastName, O.TotalAmount as TotalRevenue
FROM Orders as O
INNER JOIN Customers as C
ON O.CustomerID = C.CustomerID
GROUP BY O.OrderID, C.FirstName, C.LastName, O.TotalAmount
-- 8. Write an SQL query to list electronic gadgets and the number of times each product has been ordered. 
SELECT P.ProductName, COUNT(OD.ProductID) as NumberOfTimesOrdered
FROM OrderDetails AS OD
INNER JOIN Products AS P
ON OD.ProductID = P.ProductID
GROUP BY P.ProductName

-- 9. Write an SQL query to find customers who have purchased a specific electronic gadget product. Allow users to input the product name as a parameter. 
SELECT P.ProductName, C.FirstName, C.LastName
FROM Products as P
INNER JOIN OrderDetails AS OD
ON P.ProductID = OD.ProductID
INNER JOIN Orders AS O
ON OD.OrderID=O.OrderID
INNER JOIN Customers AS C
ON O.CustomerID = C.CustomerID
WHERE P.ProductName='Philips LED Bulb'


--10. Write an SQL query to calculate the total revenue generated by all orders placed within a specific time period. Allow users to input the start and end dates as parameters. 
SELECT SUM(TotalAmount) AS TotalRevenue FROM Orders WHERE OrderDate BETWEEN '2025-03-02' AND '2025-03-08'